// Enums for type-safe access
export enum BangladeshDivision {
  DHAKA = 'dhaka',
  CHATTOGRAM = 'chattogram',
  SYLHET = 'sylhet',
  RAJSHAHI = 'rajshahi',
  KHULNA = 'khulna',
  BARISHAL = 'barishal',
  RANGPUR = 'rangpur',
  MYMENSINGH = 'mymensingh',
}

export enum BangladeshDistrict {
  BARGUNA = 'barguna',
  BARISHAL = 'barishal',
  BHOLA = 'bhola',
  JHALOKATI = 'jhalokati',
  PATUAKHALI = 'patuakhali',
  PIROJPUR = 'pirojpur',
  BANDARBAN = 'bandarban',
  BRAHMANBARIA = 'brahmanbaria',
  CHANDPUR = 'chandpur',
  CHATTOGRAM = 'chattogram',
  CUMILLA = 'cumilla',
  COXS_BAZAR = 'coxs_bazar',
  FENI = 'feni',
  KHAGRACHHARI = 'khagrachhari',
  LAKSHMIPUR = 'lakshmipur',
  NOAKHALI = 'noakhali',
  RANGAMATI = 'rangamati',
  DHAKA = 'dhaka',
  FARIDPUR = 'faridpur',
  GAZIPUR = 'gazipur',
  GOPALGANJ = 'gopalganj',
  KISHOREGANJ = 'kishoreganj',
  MADARIPUR = 'madaripur',
  MANIKGANJ = 'manikganj',
  MUNSHIGANJ = 'munshiganj',
  NARAYANGANJ = 'narayanganj',
  NARSINGDI = 'narsingdi',
  RAJBARI = 'rajbari',
  SHARIATPUR = 'shariatpur',
  TANGAIL = 'tangail',
  BAGERHAT = 'bagerhat',
  CHUADANGA = 'chuadanga',
  JASHORE = 'jashore',
  JHENAIDAH = 'jhenaidah',
  KHULNA = 'khulna',
  KUSHTIA = 'kushtia',
  MAGURA = 'magura',
  MEHERPUR = 'meherpur',
  NARAIL = 'narail',
  SATKHIRA = 'satkhira',
  JAMALPUR = 'jamalpur',
  MYMENSINGH = 'mymensingh',
  NETROKONA = 'netrokona',
  SHERPUR = 'sherpur',
  BOGURA = 'bogura',
  CHAPAINAWABGANJ = 'chapainawabganj',
  JOYPURHAT = 'joypurhat',
  NAOGAON = 'naogaon',
  NATORE = 'natore',
  PABNA = 'pabna',
  RAJSHAHI = 'rajshahi',
  SIRAJGANJ = 'sirajganj',
  DINAJPUR = 'dinajpur',
  GAIBANDHA = 'gaibandha',
  KURIGRAM = 'kurigram',
  LALMONIRHAT = 'lalmonirhat',
  NILPHAMARI = 'nilphamari',
  PANCHAGARH = 'panchagarh',
  RANGPUR = 'rangpur',
  THAKURGAON = 'thakurgaon',
  HABIGANJ = 'habiganj',
  MOULVIBAZAR = 'moulvibazar',
  SUNAMGANJ = 'sunamganj',
  SYLHET = 'sylhet',
}

export enum BangladeshUpazila {
  AMTALI = 'amtali',
  BAMNA = 'bamna',
  BARGUNA_SADAR = 'barguna_sadar',
  BETAGI = 'betagi',
  PATHARGHATA = 'patharghata',
  TALTALI = 'taltali',
  AGAILJHARA = 'agailjhara',
  BABUGANJ = 'babuganj',
  BAKERGANJ = 'bakerganj',
  BANARIPARA = 'banaripara',
  BARISHAL_SADAR = 'barishal_sadar',
  GAURNADI = 'gaurnadi',
  HIZLA = 'hizla',
  MEHENDIGANJ = 'mehendiganj',
  MULADI = 'muladi',
  WAZIRPUR = 'wazirpur',
  BHOLA_SADAR = 'bhola_sadar',
  BURHANUDDIN = 'burhanuddin',
  CHAR_FASSON = 'char_fasson',
  DAULATKHAN = 'daulatkhan',
  LALMOHAN = 'lalmohan',
  MANPURA = 'manpura',
  TAZUMUDDIN = 'tazumuddin',
  JHALOKATI_SADAR = 'jhalokati_sadar',
  KATHALIA = 'kathalia',
  NALCHITY = 'nalchity',
  RAJAPUR = 'rajapur',
  BAUPHAL = 'bauphal',
  DASHMINA = 'dashmina',
  DUMKI = 'dumki',
  GALACHIPA = 'galachipa',
  KALAPARA = 'kalapara',
  MIRZAGANJ = 'mirzaganj',
  PATUAKHALI_SADAR = 'patuakhali_sadar',
  RANGABALI = 'rangabali',
  BHANDARIA = 'bhandaria',
  INDURKANI = 'indurkani',
  KAWKHALI_PIROJPUR = 'kawkhali_pirojpur',
  MATHBARIA = 'mathbaria',
  NAZIRPUR = 'nazirpur',
  NESARABAD = 'nesarabad',
  PIROJPUR_SADAR = 'pirojpur_sadar',
  ALI_KADAM = 'ali_kadam',
  BANDARBAN_SADAR = 'bandarban_sadar',
  LAMA = 'lama',
  NAIKHONGCHHARI = 'naikhongchhari',
  ROWANGCHHARI = 'rowangchhari',
  RUMA = 'ruma',
  THANCHI = 'thanchi',
  AKHAURA = 'akhaura',
  ASHUGANJ = 'ashuganj',
  BANCHARAMPUR = 'bancharampur',
  BIJOYNAGAR = 'bijoynagar',
  BRAHMANBARIA_SADAR = 'brahmanbaria_sadar',
  KASBA = 'kasba',
  NABINAGAR = 'nabinagar',
  NASIRNAGAR = 'nasirnagar',
  SARAIL = 'sarail',
  CHANDPUR_SADAR = 'chandpur_sadar',
  FARIDGANJ = 'faridganj',
  HAIMCHAR = 'haimchar',
  HAZIGANJ = 'haziganj',
  KACHUA_CHANDPUR = 'kachua_chandpur',
  MATLAB_DAKSHIN = 'matlab_dakshin',
  MATLAB_UTTAR = 'matlab_uttar',
  SHAHRASTI = 'shahrasti',
  ANWARA = 'anwara',
  BANSHKHALI = 'banshkhali',
  BOALKHALI = 'boalkhali',
  CHANDANAISH = 'chandanaish',
  FATIKCHHARI = 'fatikchhari',
  HATHAZARI = 'hathazari',
  KARNAPHULI = 'karnaphuli',
  LOHAGARA_CHATTOGRAM = 'lohagara_chattogram',
  MIRSHARAI = 'mirsharai',
  PATIYA = 'patiya',
  RANGUNIA = 'rangunia',
  RAOZAN = 'raozan',
  SANDWIP = 'sandwip',
  SATKANIA = 'satkania',
  SITAKUNDA = 'sitakunda',
  BARURA = 'barura',
  BRAHMANPARA = 'brahmanpara',
  BURICHANG = 'burichang',
  CHANDINA = 'chandina',
  CHAUDDAGRAM = 'chauddagram',
  CUMILLA_ADARSHA_SADAR = 'cumilla_adarsha_sadar',
  CUMILLA_SADAR_DAKSHIN = 'cumilla_sadar_dakshin',
  DAUDKANDI = 'daudkandi',
  DEBIDWAR = 'debidwar',
  HOMNA = 'homna',
  LAKSAM = 'laksam',
  LALMAI = 'lalmai',
  MEGHNA = 'meghna',
  MONOHARGONJ = 'monohargonj',
  MURADNAGAR = 'muradnagar',
  NANGALKOT = 'nangalkot',
  TITAS = 'titas',
  CHAKARIA = 'chakaria',
  COXS_BAZAR_SADAR = 'coxs_bazar_sadar',
  EIDGAON = 'eidgaon',
  KUTUBDIA = 'kutubdia',
  MAHESHKHALI = 'maheshkhali',
  PEKUA = 'pekua',
  RAMU = 'ramu',
  TEKNAF = 'teknaf',
  UKHIA = 'ukhia',
  CHHAGALNAIYA = 'chhagalnaiya',
  DAGANBHUIYAN = 'daganbhuiyan',
  FENI_SADAR = 'feni_sadar',
  FULGAZI = 'fulgazi',
  PARSHURAM = 'parshuram',
  SONAGAZI = 'sonagazi',
  DIGHINALA = 'dighinala',
  GUIMARA = 'guimara',
  KHAGRACHHARI_SADAR = 'khagrachhari_sadar',
  LAKSHMICHHARI = 'lakshmichhari',
  MAHALCHHARI = 'mahalchhari',
  MANIKCHHARI = 'manikchhari',
  MATIRANGA = 'matiranga',
  PANCHHARI = 'panchhari',
  RAMGARH = 'ramgarh',
  KAMALNAGAR = 'kamalnagar',
  LAKSHMIPUR_SADAR = 'lakshmipur_sadar',
  RAIPUR = 'raipur',
  RAMGANJ = 'ramganj',
  RAMGATI = 'ramgati',
  BEGUMGANJ = 'begumganj',
  CHATKHIL = 'chatkhil',
  COMPANIGANJ_NOAKHALI = 'companiganj_noakhali',
  HATIYA = 'hatiya',
  KABIRHAT = 'kabirhat',
  NOAKHALI_SADAR = 'noakhali_sadar',
  SENBAGH = 'senbagh',
  SONAIMURI = 'sonaimuri',
  SUBARNACHAR = 'subarnachar',
  BAGAICHHARI = 'bagaichhari',
  BARKAL = 'barkal',
  BELAICHHARI = 'belaichhari',
  JURAICHHARI = 'juraichhari',
  KAPTAI = 'kaptai',
  KAWKHALI_RANGAMATI = 'kawkhali_rangamati',
  LANGADU = 'langadu',
  NANIYACHAR = 'naniyachar',
  RAJASTHALI = 'rajasthali',
  RANGAMATI_SADAR = 'rangamati_sadar',
  DHAMRAI = 'dhamrai',
  DOHAR = 'dohar',
  KERANIGANJ = 'keraniganj',
  NAWABGANJ_DHAKA = 'nawabganj_dhaka',
  SAVAR = 'savar',
  ALFADANGA = 'alfadanga',
  BHANGA = 'bhanga',
  BOALMARI = 'boalmari',
  CHARBHADRASAN = 'charbhadrasan',
  FARIDPUR_SADAR = 'faridpur_sadar',
  MADHUKHALI = 'madhukhali',
  NAGARKANDA = 'nagarkanda',
  SADARPUR = 'sadarpur',
  SALTHA = 'saltha',
  GAZIPUR_SADAR = 'gazipur_sadar',
  KALIAKAIR = 'kaliakair',
  KALIGANJ_GAZIPUR = 'kaliganj_gazipur',
  KAPASIA = 'kapasia',
  SREEPUR_GAZIPUR = 'sreepur_gazipur',
  GOPALGANJ_SADAR = 'gopalganj_sadar',
  KASHIANI = 'kashiani',
  KOTALIPARA = 'kotalipara',
  MUKSUDPUR = 'muksudpur',
  TUNGIPARA = 'tungipara',
  AUSTAGRAM = 'austagram',
  BAJITPUR = 'bajitpur',
  BHAIRAB = 'bhairab',
  HOSSAINPUR = 'hossainpur',
  ITNA = 'itna',
  KARIMGANJ = 'karimganj',
  KATIADI = 'katiadi',
  KISHOREGANJ_SADAR = 'kishoreganj_sadar',
  KULIARCHAR = 'kuliarchar',
  MITHAMAIN = 'mithamain',
  NIKLI = 'nikli',
  PAKUNDIA = 'pakundia',
  TARAIL = 'tarail',
  DASAR = 'dasar',
  KALKINI = 'kalkini',
  MADARIPUR_SADAR = 'madaripur_sadar',
  RAJOIR = 'rajoir',
  SHIBCHAR = 'shibchar',
  DAULATPUR_MANIKGANJ = 'daulatpur_manikganj',
  GHIOR = 'ghior',
  HARIRAMPUR = 'harirampur',
  MANIKGANJ_SADAR = 'manikganj_sadar',
  SATURIA = 'saturia',
  SHIVALAYA = 'shivalaya',
  SINGAIR = 'singair',
  GAZARIA = 'gazaria',
  LOHAJANG = 'lohajang',
  MUNSHIGANJ_SADAR = 'munshiganj_sadar',
  SIRAJDIKHAN = 'sirajdikhan',
  SREENAGAR = 'sreenagar',
  TONGIBARI = 'tongibari',
  ARAIHAZAR = 'araihazar',
  BANDAR = 'bandar',
  NARAYANGANJ_SADAR = 'narayanganj_sadar',
  RUPGANJ = 'rupganj',
  SONARGAON = 'sonargaon',
  BELABO = 'belabo',
  MONOHARDI = 'monohardi',
  NARSINGDI_SADAR = 'narsingdi_sadar',
  PALASH = 'palash',
  RAIPURA = 'raipura',
  SHIBPUR = 'shibpur',
  BALIAKANDI = 'baliakandi',
  GOALANDAGHAT = 'goalandaghat',
  KALUKHALI = 'kalukhali',
  PANGSHA = 'pangsha',
  RAJBARI_SADAR = 'rajbari_sadar',
  BHEDARGANJ = 'bhedarganj',
  DAMUDYA = 'damudya',
  GOSAIRHAT = 'gosairhat',
  NARIA = 'naria',
  SHARIATPUR_SADAR = 'shariatpur_sadar',
  ZAJIRA = 'zajira',
  BASAIL = 'basail',
  BHUAPUR = 'bhuapur',
  DELDUAR = 'delduar',
  DHANBARI = 'dhanbari',
  GHATAIL = 'ghatail',
  GOPALPUR_TANGAIL = 'gopalpur_tangail',
  KALIHATI = 'kalihati',
  MADHUPUR = 'madhupur',
  MIRZAPUR = 'mirzapur',
  NAGARPUR = 'nagarpur',
  SAKHIPUR = 'sakhipur',
  TANGAIL_SADAR = 'tangail_sadar',
  BAGERHAT_SADAR = 'bagerhat_sadar',
  CHITALMARI = 'chitalmari',
  FAKIRHAT = 'fakirhat',
  KACHUA_BAGERHAT = 'kachua_bagerhat',
  MOLLAHAT = 'mollahat',
  MONGLA = 'mongla',
  MORRELGANJ = 'morrelganj',
  RAMPAL = 'rampal',
  SARANKHOLA = 'sarankhola',
  ALAMDANGA = 'alamdanga',
  CHUADANGA_SADAR = 'chuadanga_sadar',
  DAMURHUDA = 'damurhuda',
  JIBANNAGAR = 'jibannagar',
  ABHAYNAGAR = 'abhaynagar',
  BAGHERPARA = 'bagherpara',
  CHAUGACHHA = 'chaugachha',
  JASHORE_SADAR = 'jashore_sadar',
  JHIKARGACHHA = 'jhikargachha',
  KESHABPUR = 'keshabpur',
  MANIRAMPUR = 'manirampur',
  SHARSHA = 'sharsha',
  HARINAKUNDA = 'harinakunda',
  JHENAIDAH_SADAR = 'jhenaidah_sadar',
  KALIGANJ_JHENAIDAH = 'kaliganj_jhenaidah',
  KOTCHANDPUR = 'kotchandpur',
  MAHESHPUR = 'maheshpur',
  SHAILKUPA = 'shailkupa',
  BATIAGHATA = 'batiaghata',
  DACOPE = 'dacope',
  DIGHALIA = 'dighalia',
  DUMURIA = 'dumuria',
  KOYRA = 'koyra',
  PAIKGACHHA = 'paikgachha',
  PHULTALA = 'phultala',
  RUPSHA = 'rupsha',
  TEROKHADA = 'terokhada',
  BHERAMARA = 'bheramara',
  DAULATPUR_KUSHTIA = 'daulatpur_kushtia',
  KHOKSA = 'khoksa',
  KUMARKHALI = 'kumarkhali',
  KUSHTIA_SADAR = 'kushtia_sadar',
  MIRPUR_KUSHTIA = 'mirpur_kushtia',
  MAGURA_SADAR = 'magura_sadar',
  MOHAMMADPUR = 'mohammadpur',
  SHALIKHA = 'shalikha',
  SREEPUR_MAGURA = 'sreepur_magura',
  GANGNI = 'gangni',
  MEHERPUR_SADAR = 'meherpur_sadar',
  MUJIBNAGAR = 'mujibnagar',
  KALIA = 'kalia',
  LOHAGARA_NARAIL = 'lohagara_narail',
  NARAIL_SADAR = 'narail_sadar',
  ASSASUNI = 'assasuni',
  DEBHATA = 'debhata',
  KALAROA = 'kalaroa',
  KALIGANJ_SATKHIRA = 'kaliganj_satkhira',
  SATKHIRA_SADAR = 'satkhira_sadar',
  SHYAMNAGAR = 'shyamnagar',
  TALA = 'tala',
  BAKSIGANJ = 'baksiganj',
  DEWANGANJ = 'dewanganj',
  ISLAMPUR = 'islampur',
  JAMALPUR_SADAR = 'jamalpur_sadar',
  MADARGANJ = 'madarganj',
  MELANDAHA = 'melandaha',
  SARISHABARI = 'sarishabari',
  BHALUKA = 'bhaluka',
  DHOBAURA = 'dhobaura',
  FULBARIA = 'fulbaria',
  GAFARGAON = 'gafargaon',
  GAURIPUR = 'gauripur',
  HALUAGHAT = 'haluaghat',
  ISHWARGANJ = 'ishwarganj',
  MUKTAGACHHA = 'muktagachha',
  MYMENSINGH_SADAR = 'mymensingh_sadar',
  NANDAIL = 'nandail',
  PHULPUR = 'phulpur',
  TARA_KHANDA = 'tara_khanda',
  TRISHAL = 'trishal',
  ATPARA = 'atpara',
  BARHATTA = 'barhatta',
  DURGAPUR_NETROKONA = 'durgapur_netrokona',
  KALMAKANDA = 'kalmakanda',
  KENDUA = 'kendua',
  KHALIAJURI = 'khaliajuri',
  MADAN = 'madan',
  MOHANGANJ = 'mohanganj',
  NETROKONA_SADAR = 'netrokona_sadar',
  PURBADHALA = 'purbadhala',
  JHENAIGATI = 'jhenaigati',
  NAKLA = 'nakla',
  NALITABARI = 'nalitabari',
  SHERPUR_SADAR = 'sherpur_sadar',
  SREEBARDI = 'sreebardi',
  ADAMDIGHI = 'adamdighi',
  BOGURA_SADAR = 'bogura_sadar',
  DHUNAT = 'dhunat',
  DHUPCHANCHIA = 'dhupchanchia',
  GABTALI = 'gabtali',
  KAHALOO = 'kahaloo',
  NANDIGRAM = 'nandigram',
  SARIAKANDI = 'sariakandi',
  SHAJAHANPUR = 'shajahanpur',
  SHERPUR_BOGURA = 'sherpur_bogura',
  SHIBGANJ_BOGURA = 'shibganj_bogura',
  SONATOLA = 'sonatola',
  BHOLAHAT = 'bholahat',
  CHAPAINAWABGANJ_SADAR = 'chapainawabganj_sadar',
  GOMASTAPUR = 'gomastapur',
  NACHOLE = 'nachole',
  SHIBGANJ_CHAPAINAWABGANJ = 'shibganj_chapainawabganj',
  AKKELPUR = 'akkelpur',
  JOYPURHAT_SADAR = 'joypurhat_sadar',
  KALAI = 'kalai',
  KHETLAL = 'khetlal',
  PANCHBIBI = 'panchbibi',
  ATRAI = 'atrai',
  BADALGACHHI = 'badalgachhi',
  DHAMOIRHAT = 'dhamoirhat',
  MANDA = 'manda',
  MOHADEVPUR = 'mohadevpur',
  NAOGAON_SADAR = 'naogaon_sadar',
  NIAMATPUR = 'niamatpur',
  PATNITALA = 'patnitala',
  PORSHA = 'porsha',
  RANINAGAR = 'raninagar',
  SAPAHAR = 'sapahar',
  BAGATIPARA = 'bagatipara',
  BARAIGRAM = 'baraigram',
  GURUDASPUR = 'gurudaspur',
  LALPUR = 'lalpur',
  NALDANGA = 'naldanga',
  NATORE_SADAR = 'natore_sadar',
  SINGRA = 'singra',
  ATGHARIA = 'atgharia',
  BERA = 'bera',
  BHANGURA = 'bhangura',
  CHATMOHAR = 'chatmohar',
  FARIDPUR_PABNA = 'faridpur_pabna',
  ISHWARDI = 'ishwardi',
  PABNA_SADAR = 'pabna_sadar',
  SANTHIA = 'santhia',
  SUJANAGAR = 'sujanagar',
  BAGHA = 'bagha',
  BAGMARA = 'bagmara',
  CHARGHAT = 'charghat',
  DURGAPUR_RAJSHAHI = 'durgapur_rajshahi',
  GODAGARI = 'godagari',
  MOHANPUR = 'mohanpur',
  PABA = 'paba',
  PUTHIA = 'puthia',
  TANORE = 'tanore',
  BELKUCHI = 'belkuchi',
  CHAUHALI = 'chauhali',
  KAMARKHANDA = 'kamarkhanda',
  KAZIPUR = 'kazipur',
  RAIGANJ = 'raiganj',
  SHAHJADPUR = 'shahjadpur',
  SIRAJGANJ_SADAR = 'sirajganj_sadar',
  TARASH = 'tarash',
  ULLAHPARA = 'ullahpara',
  BIRAMPUR = 'birampur',
  BIRGANJ = 'birganj',
  BIRAL = 'biral',
  BOCHAGANJ = 'bochaganj',
  CHIRIRBANDAR = 'chirirbandar',
  DINAJPUR_SADAR = 'dinajpur_sadar',
  GHORAGHAT = 'ghoraghat',
  HAKIMPUR = 'hakimpur',
  KAHAROLE = 'kaharole',
  KHANSAMA = 'khansama',
  NAWABGANJ_DINAJPUR = 'nawabganj_dinajpur',
  PARBATIPUR = 'parbatipur',
  PHULBARI_DINAJPUR = 'phulbari_dinajpur',
  GAIBANDHA_SADAR = 'gaibandha_sadar',
  GOBINDAGANJ = 'gobindaganj',
  PALASHBARI = 'palashbari',
  PHULCHHARI = 'phulchhari',
  SADULLAPUR = 'sadullapur',
  SUGHATTA = 'sughatta',
  SUNDARGANJ = 'sundarganj',
  BHURUNGAMARI = 'bhurungamari',
  CHAR_RAJIBPUR = 'char_rajibpur',
  CHILMARI = 'chilmari',
  KURIGRAM_SADAR = 'kurigram_sadar',
  NAGESHWARI = 'nageshwari',
  PHULBARI_KURIGRAM = 'phulbari_kurigram',
  RAJARHAT_KURIGRAM = 'rajarhat_kurigram',
  RAOMARI = 'raomari',
  ULIPUR = 'ulipur',
  ADITMARI = 'aditmari',
  HATIBANDHA = 'hatibandha',
  KALIGANJ_LALMONIRHAT = 'kaliganj_lalmonirhat',
  LALMONIRHAT_SADAR = 'lalmonirhat_sadar',
  PATGRAM = 'patgram',
  DIMLA = 'dimla',
  DOMAR = 'domar',
  JALDHAKA = 'jaldhaka',
  KISHOREGANJ_NILPHAMARI = 'kishoreganj_nilphamari',
  NILPHAMARI_SADAR = 'nilphamari_sadar',
  SAIDPUR = 'saidpur',
  ATWARI = 'atwari',
  BODA = 'boda',
  DEBIGANJ = 'debiganj',
  PANCHAGARH_SADAR = 'panchagarh_sadar',
  TETULIA = 'tetulia',
  BADARGANJ = 'badarganj',
  GANGACHHARA = 'gangachhara',
  KAUNIA = 'kaunia',
  MITHAPUKUR = 'mithapukur',
  PIRGACHHA = 'pirgachha',
  PIRGANJ_RANGPUR = 'pirganj_rangpur',
  RANGPUR_SADAR = 'rangpur_sadar',
  TARAGANJ = 'taraganj',
  BALIADANGI = 'baliadangi',
  HARIPUR = 'haripur',
  PIRGANJ_THAKURGAON = 'pirganj_thakurgaon',
  RANISANKAIL = 'ranisankail',
  THAKURGAON_SADAR = 'thakurgaon_sadar',
  AJMIRIGANJ = 'ajmiriganj',
  BAHUBAL = 'bahubal',
  BANIYACHONG = 'baniyachong',
  CHUNARUGHAT = 'chunarughat',
  HABIGANJ_SADAR = 'habiganj_sadar',
  LAKHAI = 'lakhai',
  MADHABPUR = 'madhabpur',
  NABIGANJ = 'nabiganj',
  SHAYESTAGANJ = 'shayestaganj',
  BARLEKHA = 'barlekha',
  JURI = 'juri',
  KAMALGANJ = 'kamalganj',
  KULAURA = 'kulaura',
  MOULVIBAZAR_SADAR = 'moulvibazar_sadar',
  RAJNAGAR = 'rajnagar',
  SREEMANGAL = 'sreemangal',
  BISHWAMVARPUR = 'bishwamvarpur',
  CHHATAK = 'chhatak',
  DERAI = 'derai',
  DHARAMAPASHA = 'dharamapasha',
  DOWARABAZAR = 'dowarabazar',
  JAGANNATHPUR = 'jagannathpur',
  JAMALGANJ = 'jamalganj',
  MADHYANAGAR = 'madhyanagar',
  SHANTIGANJ = 'shantiganj',
  SULLAH = 'sullah',
  SUNAMGANJ_SADAR = 'sunamganj_sadar',
  TAHIRPUR = 'tahirpur',
  BALAGANJ = 'balaganj',
  BEANIBAZAR = 'beanibazar',
  BISHWANATH = 'bishwanath',
  COMPANIGANJ_SYLHET = 'companiganj_sylhet',
  DAKSHIN_SURMA = 'dakshin_surma',
  FENCHUGANJ = 'fenchuganj',
  GOLAPGANJ = 'golapganj',
  GOWAINGHAT = 'gowainghat',
  JAINTIAPUR = 'jaintiapur',
  KANAIGHAT = 'kanaighat',
  OSMANI_NAGAR = 'osmani_nagar',
  SYLHET_SADAR = 'sylhet_sadar',
  ZAKIGANJ = 'zakiganj',
}

// Coordinates interface for geo-location
export interface Coordinates {
  latitude: number;
  longitude: number;
}

// Base location interface
export interface BaseLocation {
  id: number;
  name: string;
  bnName: string;
  slug: string;
}

// Division interface with additional metadata
export interface Division extends BaseLocation {
  coordinates?: Coordinates;
  area?: number; // in sq km
  population?: number;
  literacy?: number; // percentage
}

// District interface with division reference
export interface District extends BaseLocation {
  divisionId: number;
  coordinates?: Coordinates;
  area?: number;
  population?: number;
  postalCode?: string; // Postal code range (e.g., "8700-8799")
}

// Upazila interface with district reference
export interface Upazila extends BaseLocation {
  districtId: number;
  coordinates?: Coordinates;
  area?: number;
  population?: number;
  postalCode?: string; // Specific 4-digit postal code
}

// Union interface with upazila reference
export interface Union extends BaseLocation {
  upazilaId: number;
  coordinates?: Coordinates;
  area?: number;
  population?: number;
}

// Full address information
export interface FullAddress {
  division: Division;
  district: District;
  upazila: Upazila;
  union?: Union;
}

// Postal information for a location
export interface PostalInfo {
  postalCode: string;    // Specific upazila postal code (e.g., "1340")
  districtRange: string; // District postal code range (e.g., "1000-1399")
}

// Search result types
export interface SearchResult<T> {
  item: T;
  score: number;
  matchedField: 'name' | 'bnName' | 'slug';
}

export interface LocationSearchResult {
  divisions: SearchResult<Division>[];
  districts: SearchResult<District>[];
  upazilas: SearchResult<Upazila>[];
  unions: SearchResult<Union>[];
}

// Location type for unified operations
export type LocationType = 'division' | 'district' | 'upazila' | 'union';
export type AnyLocation = Division | District | Upazila | Union;

// Statistics interface
export interface LocationStats {
  totalDivisions: number;
  totalDistricts: number;
  totalUpazilas: number;
  totalUnions: number;
  divisionDistrictMap: Record<number, number>;
  districtUpazilaMap: Record<number, number>;
  upazilaUnionMap: Record<number, number>;
}